### ISSUE TITLE
Update ArgyllCMS to v2.3.0 -- Fix Spyder X support

### ISSUE THREAD

**Issue by ShapeShifter499** [flathub/net.displaycal.DisplayCAL#3]
After some messing around and trying in Windows and Arch Linux with the Flatpak package, I found that the Spyder X would measure once and then stop with "communications failure" until I unplugged and plugged in the device again.

After some searching I found that there was a change in ArgyllCMS that gets around that quirk by resetting the connection. Mentioned here: https://hub.displaycal.net/forums/topic/error-instrument-access-failed-for-lcd-white-led-mode/

When the Windows version of DisplayCAL is pointed to the newer ArgyllCMS v2.3.0 executables things appear to work fine.

I suspect that this flatpak needs updating to ArgyllCMS v2.3.0 to fix my issue.

I'm only using the flatpak on Arch Linux because of some, at the time of writing, repository issues with 'python-wxpython' and multiple other packages.

**Comment by hfiguiere** [comment]
See #1: a new test build will appear in a bit. Let me now if that fixes it for you.

**Comment by hfiguiere** [comment]
(unless it fails on aarch64 when I tried to update argyllcms, in that case it will take a bit longer)

**Comment by ShapeShifter499** [comment]
> (unless it fails on aarch64 when I tried to update argyllcms, in that case it will take a bit longer)

Kind of looks like it already will fail looking at the latest build log.

**Comment by hfiguiere** [comment]
it did. *sigh*

**Comment by hfiguiere** [comment]
there is a build now. If you can tell me if it fixes your problem.

**Comment by ShapeShifter499** [comment]
> there is a build now. If you can tell me if it fixes your problem.

```flatpak install --user https://dl.flathub.org/build-repo/93491/net.displaycal.DisplayCAL.flatpakref```

This seems to work great. I can do multiple measurement without needing to reconnect my Spyder X and no more 'communication failure' errors.

Updating Argyll fixes my issue

**Comment by ShapeShifter499** [comment]
Thank you for updating this
